[tool.poetry]
name = "Benchmark"
version = "0.1.0"
description = ""
authors = ["kired2806 <nour-elhouda.kired@univ-tlse3.Fr>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22.2"
tqdm = "^4.62.3"
six = "^1.16.0"
pandas = "^1.4.2"
matplotlib = "^3.5.1"
plotly = "^5.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
