[tool.poetry]
name = "data-generator"
version = "0.1.0"
description = ""
authors = ["NourKired <nada.kired@gmail.com>"]

[tool.poetry.dependencies]
python = "3.10"
numpy = "^1.22.4"
six = "^1.16.0"
tqdm = "^4.64.0"
scipy = "^1.8.1"
click = "^8.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
